name: Run it on push

on:
  push:

jobs:
  snaplinks:
    name: Snapshot links for certain keywords
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install git+git://github.com/elisong/script-blocks.git
      - name: Google keywords
        run: |
          git update-index --chmod=+x ./snap.sh
          ./snap.sh
        shell: bash
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Eli Song
          author_email: elisong.ah@gmail.com
          message: "auto commit"
          add: "*.md"
